dependencies:
- about-time==4.2.1
- absl-py==1.4.0
- aiosignal==1.3.1
- alive-progress==3.1.4
- asttokens==2.2.1
- astunparse==1.6.3
- attrs==23.2.0
- autograd==1.6.2
- backcall==0.2.0
- basemap==1.4.1
- basemap-data==1.3.2
- cachetools==5.3.1
- Cartopy==0.23.0
- certifi==2023.5.7
- charset-normalizer==3.1.0
- ci-info==0.3.0
- clarabel==0.9.0
- click==8.1.7
- click-plugins==1.1.1
- cligj==0.7.2
- cloudpickle==2.2.1
- cma==3.2.2
- colorama==0.4.6
- comm==0.1.4
- configobj==5.0.8
- configparser==7.0.0
- contourpy==1.3.0
- cvxpy==1.5.3
- cycler==0.10.0
- deap==1.4.1
- debugpy==1.6.8
- decorator==5.1.1
- Deprecated==1.2.14
- dill==0.3.7
- ecos==2.0.14
- et-xmlfile==1.1.0
- etelemetry==0.3.1
- executing==1.2.0
- filelock==3.14.0
- fiona==1.9.5
- fitz==0.0.1.dev2
- flatbuffers==24.3.25
- fonttools==4.55.1
- frozenlist==1.4.1
- fsspec==2024.9.0
- future==0.18.3
- gast==0.4.0
- geopandas==0.14.3
- google-auth==2.21.0
- google-auth-oauthlib==1.0.0
- google-pasta==0.2.0
- goto-statement==1.2
- grapheme==0.6.0
- grpcio==1.56.0
- gym==0.26.2
- gym-notices==0.0.8
- h5py==3.12.1
- httplib2==0.22.0
- idna==3.4
- importlib-metadata==6.7.0
- importlib_resources==6.4.5
- ipykernel==6.25.0
- ipython==8.14.0
- isodate==0.6.1
- jax==0.4.13
- jedi==0.19.0
- Jinja2==3.1.4
- joblib==1.3.2
- jsonschema==4.23.0
- jsonschema-specifications==2024.10.1
- jupyter_client==8.3.0
- jupyter_core==5.3.1
- keras==2.12.0
- Keras-Preprocessing==1.1.2
- kiwisolver==1.3.1
- libclang==16.0.0
- llvmlite==0.42.0
- looseversion==1.3.0
- lxml==5.2.2
- Markdown==3.4.3
- markdown-it-py==3.0.0
- MarkupSafe==2.1.3
- matplotlib==3.4.3
- matplotlib-inline==0.1.6
- mdurl==0.1.2
- ml-dtypes==0.4.1
- mpmath==1.3.0
- msgpack==1.1.0
- multiprocess==0.70.15
- namex==0.0.8
- nest-asyncio==1.5.7
- networkx==3.2.1
- nibabel==5.2.1
- nipype==1.8.6
- numba==0.59.1
- numpy==1.22.4
- oauthlib==3.2.2
- opencv-python==4.7.0.68
- openpyxl==3.1.0
- opt-einsum==3.3.0
- optree==0.13.0
- osqp==0.6.7.post1
- packaging==23.1
- pandas==2.2.3
- parso==0.8.3
- pathlib==1.0.1
- pathos==0.3.1
- pickleshare==0.7.5
- Pillow==8.2.0
- platformdirs==3.10.0
- pox==0.3.3
- ppft==1.7.6.7
- prompt-toolkit==3.0.39
- protobuf==4.25.5
- prov==2.0.0
- psutil==5.9.5
- pure-eval==0.2.2
- pyaml==24.9.0
- pyasn1==0.5.0
- pyasn1-modules==0.3.0
- pydot==2.0.0
- Pygments==2.15.1
- pymoo==0.6.0.1
- pymop==0.2.4
- PyMuPDF==1.24.4
- PyMuPDFb==1.24.3
- pynndescent==0.5.12
- pyparsing==3.1.2
- pyproj==3.6.1
- pyshp==2.3.1
- python-dateutil==2.8.2
- python-pptx==0.6.23
- pytz==2022.2.1
- pywin32==306
- pyxnat==1.6.2
- PyYAML==6.0.2
- pyzmq==25.1.0
- qdldl==0.1.7.post4
- ray==2.37.0
- rdflib==7.0.0
- referencing==0.35.1
- requests==2.31.0
- requests-oauthlib==1.3.1
- rich==13.9.2
- rpds-py==0.20.0
- rsa==4.9
- scikit-learn==1.3.0
- scikit-optimize==0.10.2
- scipy==1.7.1
- scs==3.2.7
- seaborn==0.13.2
- shapely==2.0.2
- simplejson==3.19.2
- six==1.15.0
- stack-data==0.6.2
- sympy==1.13.3
- tensorboard==2.12.3
- tensorboard-data-server==0.7.2
- tensorboard-plugin-wit==1.8.1
- tensorflow==2.12.0
- tensorflow-estimator==2.12.0
- tensorflow-intel==2.12.0
- tensorflow-io-gcs-filesystem==0.31.0
- termcolor==2.3.0
- threadpoolctl==3.2.0
- tk==0.1.0
- torch==2.4.1
- torchvision==0.19.1
- tornado==6.3.2
- tqdm==4.66.4
- traitlets==5.9.0
- traits==6.3.2
- typing_extensions==4.12.2
- tzdata==2024.2
- umap-learn==0.5.6
- urllib3==1.26.16
- wcwidth==0.2.6
- Werkzeug==2.3.6
- wrapt==1.14.1
- xlrd==2.0.1
- XlsxWriter==3.2.0
- xlwt==1.3.0
- zipp==3.15.0

